### ISSUE TITLE
Bug or not

### ISSUE THREAD

**Issue by omfgnuts** [Bryukh-Checkio-Tasks/checkio-task-three-points-circle#4]
если будут подозрения на баг, я просто сюда буду постить, чтобы не дергать по чатам\почте http://www.checkio.org/forum/post/3473/it-must-be-a-bug-but-from-whom/

**Comment by Bryukh** [comment]
Да, но я решил его лучше вообще удалить, так как этот тест был недавно добавлен и спорный
